version: '3.8'

services:
  app_sys01:
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - APP_NAME=SYS01
    volumes:
      - ./log:/usr/src/app/log

  app_sys02:
    build: .
    ports:
      - "${PORT2}:${PORT2}"
    environment:
      - PORT=${PORT2}
      - APP_NAME=SYS02
    volumes:
      - ./log:/usr/src/app/log
